python-2/django/integration_project/apps/course_app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^delete/(?P<id>(\d+))/(?P<verification>(\w+))$', views.delete, name='verify-delete'),
    url(r'^delete_course/(?P<id>\d+)$', views.delete_course, name='delete'),
    url(r'^add_course?$', views.add_course, name='add'),
    url(r'^$', views.index, name='index'),
    url(r'^enroll$', views.enroll, name='enroll'),
    url(r'^enroll_user$', views.enroll_user, name='enroll_user'),

]

python-2/django/integration_project/apps/login_reg_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^users/new$', views.process, name='process'),
	url(r'^users/login$', views.login, name='login'),
	url(r'^delete_user/(?P<id>\d+)$', views.delete_user, name='delete_user'),
	url(r'^manage_user/$', views.manage_user, name='manage_user'),	
	
]

python-2/django/integration_project/apps/ninjaGold_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^process_money$', views.process_money, name='process'),
    url(r'^', views.index, name='index'),

]

python-2/django/integration_project/integration_project/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.login_reg_app.urls', namespace ="login")),
	url(r'^ninja-gold/', include('apps.ninjaGold_app.urls', namespace ="ninja-gold")),
	url(r'^random-word/', include('apps.randomWord.urls', namespace ="random-word")),
	url(r'^time-display/', include('apps.timedisplay.urls', namespace ="time-display")),
	url(r'^courses/', include('apps.course_app.urls', namespace ="courses")),
]


    

python-2/django/integration_project/apps/ninjaGold_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

python-2/django/integration_project/apps/ninjaGold_app/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.core.urlresolvers import reverse
import os, random
import datetime


activities=[]

def index(request):
	if 'gold' not in request.session:
		request.session['gold']=0
		request.session['activities']=""
	return render(request, 'ninjaGold/index.html')

def process_money(request):
	if request.method == "POST":
		print "Got post"
		now= datetime.datetime.now()
		date = str(now.strftime('(%m/%d/%y at %I:%M:%S %p)'))
		if (request.POST['building'] == "farm"):
			delta=random.randrange(10,21) #farm
			request.session['gold']+= delta
			activity = {
				'results': "Earned "+str(delta)+" golds from the farm!",
				'date': date
			}
		elif (request.POST['building'] == "cave"):
			delta=random.randrange(5,11) #cave
			request.session['gold']+= delta
			activity = {
				'results': "Earned "+str(delta)+" golds from the cave!",
				'date': date
			}	
		elif (request.POST['building'] == "house"):
			delta=random.randrange(2,6) #house
			request.session['gold']+= delta
			activity = {
				'results': "Earned "+str(delta)+" golds from the house!",
				'date': date
			}	
		elif (request.POST['building'] == "casino"):
			delta=random.randrange(-50,51) #casino
			request.session['gold']+= delta
			if (delta < 0):
				activity = {
					'results': "Lost "+str(delta)+" golds to the casino!",
					'date': date
				}	
			else:
				activity = {
				'results': "Earned "+str(delta)+" golds from the casino!",
				'date': date
				}	
		activities.insert(0, activity)
		request.session['activities']=activities	
		print activities
		return redirect (reverse('ninja-gold:index'))





















	

python-2/django/integration_project/apps/ninjaGold_app/templates/ninjaGold/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Ninja Gold</title>
	<meta charset="utf-8">
	<!-- Latest boostrap compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'ninjaGold/css/style.css' %}">
</head>
<body>
	<div class="container">
	<div id="navbar">
      <ul>
        <li><a href=" {% url 'courses:index' %} ">Manage (add/delete) Courses</a></li>
        <li><a href=" {% url 'login:manage_user' %} ">Manage Users</a></li> 
        <li><a href=" {% url 'courses:enroll' %} ">Enroll Users </a></li>  
        <li><a href=" {% url 'time-display:index' %} ">Time-Display</a></li>
        <!-- <li><a href=" {% url 'ninja-gold:index' %} ">Ninja-Gold</a></li> -->
        <li><a href=" {% url 'random-word:index' %} ">Random Word</a></li>
      </ul>
 </div> <!-- end navbar -->
		<div class="box">
			<h1>Ninja Money</h1>
			<table id="amt_gold">
				<tr>
					<td>Your Gold:</td>
					<td>{{request.session.gold}}</td>
				</tr>
			</table>
			
			<div class="form_area" id="farm">
				<h3>Farm</h3>
				<h4>(earns 10-20 golds)</h4>
				<form action="{% url 'ninja-gold:process'%}" method="post">
				{% csrf_token %}
					 <input type="hidden" name="building" value="farm" />
					 <input class="btn btn-primary" type="submit" value="Find Gold!"/>
				</form> 
			</div> <!-- end form area -->
			<div class="form_area" id="cave">
				<h3>Cave</h3>
				<h4>(earns 5-10 golds)</h4>
				<form action="{% url 'ninja-gold:process'%}" method="post">
				{% csrf_token %}
					 <input type="hidden" name="building" value="cave" />
					 <input class="btn btn-primary" type="submit" value="Find Gold!"/>
				</form> 
			</div> <!-- end form area -->
			<div class="form_area" id="house">
				<h3>House</h3>
				<h4>(earns 2-5 golds)</h4>
				<form action="{% url 'ninja-gold:process'%}" method="post">
				{% csrf_token %}
					 <input type="hidden" name="building" value="house" />
					 <input class="btn btn-primary" type="submit" value="Find Gold!"/>
				</form> 
			</div> <!-- end form area -->
			<div class="form_area" id="casino">
				<h3>Casino</h3>
				<h4>(gamble 0-50 golds)</h4>
				<form action="{% url 'ninja-gold:process'%}" method="post">
				{% csrf_token %}
					 <input type="hidden" name="building" value="casino" />
					 <input class="btn btn-primary" type="submit" value="Find Gold!"/>
				</form> 
			</div> <!-- end form area -->
			<h2>Activities:</h2>
			<div id="scrollbox">
				{% for item in request.session.activities %}
					{{ item.results }} {{ item.date }}
					<br>
				{% endfor %}			
			</div>

		<div id="filler"> </div> 
		</div> <!-- end box -->
	</div> <!-- end container -->
	
</body>
</html>