python-2/django/integration_project/apps/course_app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^delete/(?P<id>(\d+))/(?P<verification>(\w+))$', views.delete, name='verify-delete'),
    url(r'^delete_course/(?P<id>\d+)$', views.delete_course, name='delete'),
    url(r'^add_course?$', views.add_course, name='add'),
    url(r'^$', views.index, name='index'),
    url(r'^enroll$', views.enroll, name='enroll'),
    url(r'^enroll_user$', views.enroll_user, name='enroll_user'),

]

python-2/django/integration_project/apps/login_reg_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^users/new$', views.process, name='process'),
	url(r'^users/login$', views.login, name='login'),
	url(r'^delete_user/(?P<id>\d+)$', views.delete_user, name='delete_user'),
	url(r'^manage_user/$', views.manage_user, name='manage_user'),	
	
]

python-2/django/integration_project/integration_project/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.login_reg_app.urls', namespace ="login")),
	url(r'^ninja-gold/', include('apps.ninjaGold_app.urls', namespace ="ninja-gold")),
	url(r'^random-word/', include('apps.randomWord.urls', namespace ="random-word")),
	url(r'^time-display/', include('apps.timedisplay.urls', namespace ="time-display")),
	url(r'^courses/', include('apps.course_app.urls', namespace ="courses")),
]


    

python-2/django/integration_project/apps/course_app/models.py
from __future__ import unicode_literals

from django.db import models
from ..login_reg_app.models import User

class Course(models.Model):
	catalogNo = models.SmallIntegerField()
	name = models.CharField(max_length=45)
	description = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	users = models.ManyToManyField(User)
	

python-2/django/integration_project/apps/course_app/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.db.models import Count
from .models import Course 
from ..login_reg_app.models import User


# Create your views here.
def index(request):
    courses = Course.objects.all()
    # print "courses:", courses

    # print ("query:", 50*"*")
    # print courses.query
    # print ("object:",50*"*")
    # print courses
    # print (50*"*")
    # for course in courses:
    #     print course.name, course.description

    context = {
        'courses': courses
    }
    return render(request, 'course_app/index.html', context)


def add_course(request):
    if request.method == "POST":
        print "Got add post" 
        course_number = request.POST['catalogNo']
        course_name = request.POST['name']
        course_description = request.POST['description']
        print course_name   
        print course_description
        Course.objects.create(catalogNo=course_number, name=course_name, description=course_description)
    return redirect (reverse('courses:index'))


def delete_course(request, id):
    print "Got delete request" 
    courses = Course.objects.filter(id=id)
    
    print ("query:", 50*"*")
    print courses.query
    print ("object:",50*"*")
    print courses
    print (50*"*")
    for course in courses:
        print course.name, course.description

    context = {
        'courses': courses
    }

    return render(request, 'course_app/verify.html', context)

       
def delete(request, id, verification):
    print "Got delete command"
    print verification 
    if verification == "confirm":
        Course.objects.filter(id=id).delete()
    return redirect (reverse('courses:index'))

def enroll(request):
    print "In enroll method"
    courses = Course.objects.annotate(num_users = Count('users'))
    users = User.objects.all()
    context = {
        'courses': courses,
        'users': users
    }

    return render(request, 'course_app/enroll.html', context)


def enroll_user(request):
    error=False
    print "request.POST['user_id']", request.POST['user_id']
    print "request.POST['course_id']", request.POST['course_id']

    if request.POST['course_id']=="Courses":
        messages.add_message(request, messages.INFO,"You need to select a course")
        error=True
    if request.POST['user_id']=="Users":
        messages.add_message(request, messages.INFO,"You need to select a user")
        error=True

    if not error:
        try:
            this_enrollment = Course.objects.get(id=request.POST['course_id'], users=request.POST['user_id'])
        except Course.DoesNotExist:
            this_enrollment = Course.objects.get(id=request.POST['course_id'])
            this_enrollment.users.add(request.POST['user_id'])
            print"Added user_id:{} to course_id{}".format(request.POST['user_id'], request.POST['course_id']) 
            return redirect (reverse('courses:enroll'))
        else:
            this_course = Course.objects.filter(id=request.POST['course_id']).values()
            this_user = User.objects.filter(id=request.POST['user_id']).values()    
            print"this_enrollment", this_course[0]
            messages.add_message(request, messages.INFO, "{} {} is already signed up for {}".format(this_user[0]['first_name'], this_user[0]['last_name'], this_course[0]['name']) )
            return redirect (reverse('courses:enroll'))
    else:
        messages.add_message(request, messages.INFO, "Please try again")
        print"we got error messages"
        return redirect (reverse('courses:enroll'))
            

    
   

python-2/django/integration_project/apps/course_app/templates/course_app/enroll.html
<!DOCTYPE html>
<html>
<head>
	<title>Enroll</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'course_app/css/style.css' %}">

</head>
<body>
<div id='container'>
	<div id="navbar">
      <ul>
        <li><a href=" {% url 'courses:index' %} ">Manage (add/delete) Courses</a></li>
        <li><a href=" {% url 'login:manage_user' %} ">Manage Users</a></li> 
        <!-- <li><a href=" {% url 'courses:enroll' %} ">Enroll Users </a></li>   -->
        <li><a href=" {% url 'time-display:index' %} ">Time-Display</a></li>
        <li><a href=" {% url 'ninja-gold:index' %} ">Ninja-Gold</a></li>
        <li><a href=" {% url 'random-word:index' %} ">Random Word</a></li>
      </ul>
 </div> <!-- end navbar -->

	<div id='index_inset'>
		<h1>Enroll user in a course</h1>
		<div id='enroll_area'>
			<h2>User/Course Selection:</h2>
			<form action="{% url 'courses:enroll_user' %}" id='course_form' method="post">
				{% csrf_token %}			
				<table id='select_table'>
					<tr>
						<th>Course (select one):</th>
						<th>Users(select one):</th>
						<th></th>
					</tr>
					<tr>
						<td>
							<select class="form-control" id="sel1" name="course_id">
							<option selected="selected" class="holder">Courses</option>
						    {% for course in courses %}
							    <option value="{{course.id}}">{{course.id}} {{course.catalogNo}} {{course.name}} </option> 
						    {% endfor %}
						    </select>
						</td>
						<td>
							<select class="form-control" id="sel2" name="user_id">>
							<option selected="selected" class="holder">Users</option>
							{% for user in users %}
								<option value="{{user.id}}">{{user.id}} {{user.first_name}} {{user.last_name}}</option>
							{% endfor %}
							</select>
						</td>
						<td>
							<input id='submit_btn_er' class="btn btn-primary" type="submit" value="Add User To Course">
						</td>
					</tr>
				</table>			
			</form>
			{% if messages %}
			<ul class="messages">
			    {% for message in messages %}
			    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			    {% endfor %}
			</ul>
			{% endif %}
		</div>
		<div id='summary_display'>
			<h2>Courses</h2>
			<table class="table table-bordered">
				<tr>
					<th>Course</th><th>Title</th><th>Number of Users</th>
				</tr>
				{% for course in courses %}
				<tr>
					<td>{{course.catalogNo}}</td>
					<td>{{course.name}}</td>
					<!-- <td>{{course.users}}</td> -->	
					<td>{{course.num_users}}</td>					
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>
</div>
</body>
</html>

python-2/django/integration_project/apps/course_app/templates/course_app/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Manage Courses</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'course_app/css/style.css' %}">

</head>
<body>
<div id='container'>
	<div id="navbar">
      <ul>
        <!-- <li><a href=" {% url 'courses:index' %} ">Manage (add/delete) Courses</a></li> -->
        <li><a href=" {% url 'login:manage_user' %} ">Manage Users</a></li> 
        <li><a href=" {% url 'courses:enroll' %} ">Enroll Users </a></li>  
        <li><a href=" {% url 'time-display:index' %} ">Time-Display</a></li>
        <li><a href=" {% url 'ninja-gold:index' %} ">Ninja-Gold</a></li>
        <li><a href=" {% url 'random-word:index' %} ">Random Word</a></li>
      </ul>
 </div> <!-- end navbar -->

	<div id='index_inset'>
		<h1>Manage (add/delete) student courses</h1>
		<div id='input_area'>
			<h2>Add a new course</h2>
			<form action="add_course" id='course_form' method="POST">
				{% csrf_token %}
				<table>
					<tr>
						<td>Catalog No: </td>
						<td><input type="text" name="catalogNo"></td>
					</tr>
					<tr>
						<td>Name: </td>
						<td><input type="text" name="name"></td>
					</tr>
					<tr>
						<td>Description:</td>
						<td><textarea name="description" form='course_form'></textarea></td>
					</tr>
				</table>
				<input id='submit_btn' class="btn btn-primary" type="submit" name="Add">			
			</form>
		</div>
		<div id='summary_display'>
			<h2>Courses</h2>
			<table class="table table-bordered">
				<tr>
					<th>Course</th><th>Title</th><th>Description</th><th>Date Added</th><th>Actions</th>
				</tr>
				{% for course in courses %}
				<tr>
					<td>{{course.catalogNo}}</td>
					<td>{{course.name}}</td>
					<td>{{course.description}}</td>
					<td>{{ course.created_at}}</td>
					<td><a href="delete_course/{{course.id}}", method='POST'>delete</a></td>
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>
</div>
</body>
</html>

python-2/django/integration_project/apps/course_app/templates/course_app/verify.html
<!DOCTYPE html>
<html>
<head>
	<title>Courses</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'course_app/css/style.css' %}">

</head>
<body>
<div id='container'>

	<div id='verify_inset'>
		<h1>Delete a course</h1>
		<div id="verify">
			<h2>Are you sure you want to delete the following course?</h2>
			{% for course in courses %}
			<table>
					<tr>
						<td>Name: </td><td>{{course.name}}</td>				
					</tr>
					<tr>
						<td>Description:</td><td>{{course.description}}</td>
					</tr>
				</table>
			
		</div>
		<form action="{% url 'courses:verify-delete' id=course.id verification='cancel' %}" id='cancel' method="POST">
		{% csrf_token %}
			<button  id='submit_btn_no' class="btn btn-primary" type="submit" name="no">No</button>
		</form>
		<form action="{% url 'courses:verify-delete' id=course.id verification='confirm' %}" id='confirm' method="POST">
		{% csrf_token %}	
			<button action="courses:delete/{{course.id}}/confirm" id='submit_btn_ok' class="btn btn-danger" type="submit" name="yes">Yes! I want to delete this</button>
		</form>
		{% endfor %}
	</div> 
</div>
</body>
</html>