python-2/django/integration_project/apps/course_app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^delete/(?P<id>(\d+))/(?P<verification>(\w+))$', views.delete, name='verify-delete'),
    url(r'^delete_course/(?P<id>\d+)$', views.delete_course, name='delete'),
    url(r'^add_course?$', views.add_course, name='add'),
    url(r'^$', views.index, name='index'),
    url(r'^enroll$', views.enroll, name='enroll'),
    url(r'^enroll_user$', views.enroll_user, name='enroll_user'),

]

python-2/django/integration_project/apps/login_reg_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^users/new$', views.process, name='process'),
	url(r'^users/login$', views.login, name='login'),
	url(r'^delete_user/(?P<id>\d+)$', views.delete_user, name='delete_user'),
	url(r'^manage_user/$', views.manage_user, name='manage_user'),	
	
]

python-2/django/integration_project/integration_project/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.login_reg_app.urls', namespace ="login")),
	url(r'^ninja-gold/', include('apps.ninjaGold_app.urls', namespace ="ninja-gold")),
	url(r'^random-word/', include('apps.randomWord.urls', namespace ="random-word")),
	url(r'^time-display/', include('apps.timedisplay.urls', namespace ="time-display")),
	url(r'^courses/', include('apps.course_app.urls', namespace ="courses")),
]


    

python-2/django/integration_project/apps/login_reg_app/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.exceptions import ObjectDoesNotExist
import bcrypt, re

# Create your models here.
class UserManager(models.Manager):

    def validate_registration(self, *args):
        print"in validate_registration"
        print"*********"
        print "args:", args
        print"*********"
        first_name=args[0]['ufname']
        last_name=args[0]['ulname']
        email=args[0]['uemail']
        password=args[0]['password']
        confirm_pwd=args[0]['confirm_pwd']

        print("variables:", first_name, last_name, email, password, confirm_pwd)
        
        errors=[]
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')

        if not email:
            errors.append("Email cannot be blank!")
        elif not EMAIL_REGEX.match(email):
            errors.append("Invalid Email Address!")

        if not first_name:
            errors.append("Need to include first name")
        if not last_name:
            errors.append("Need to include last name")      
        if  re.search(r"\d", first_name) or re.search(r"\d", last_name):
            errors.append("Names cannot contain numerals")  
        if not email:
            errors.append("Email cannot be blank!")
        elif not EMAIL_REGEX.match(email):
            errors.append("Invalid Email Address!")
        if not password:
            errors.append("Need to include password")  
        if not confirm_pwd:
            errors.append("Please confirm password")    
        if (len(password) >0 and len(confirm_pwd) >0):
            if password != confirm_pwd:
                errors.append("Password and Confirmation Password does not match") 
            if len(password) < 8:
                 errors.append("Passwords need to contain at least 8 characters") 

        try:
            user = User.objects.get(email=email)
        except ObjectDoesNotExist: 
            pass
        else:
            errors.append("User with that email ({}) already exists in our database".format(email))
            return(False, errors) 

        if not errors:
            pw_hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
            print{"********pw_hashed********"}
            print(pw_hashed)
            user = User(first_name=first_name, last_name=last_name, email=email, pw_hash=pw_hashed)
            user.save()
            user = User.objects.filter(email=email).values() # .values() returns dictionary of elements in list[0]
                        
            # for debug
            users= User.objects.all()
            print("query return:", users)
            for user in users:
              print(user)
            # end for debug

            return(True, user)
        else:
            return(False, errors) 

    def validate_login(self, *args):
        errors=[]
        print"in validate_login"
        print"*********"
        print "args:", args
        print"*********"   
        email=args[0]['user_email']
        password=args[0]['password']
        try:
            # user = User.objects.get(email=email).values()
            user = User.objects.filter(email=email).values()
            print"try query return for {}:{}".format(email, user)
        except ObjectDoesNotExist:
            errors.append("No such user ({}) exists in our database".format(email))
            print "No such user ({}) exists in our database".format(email)
            return(False, errors) 
               
        if bcrypt.hashpw(password.encode(), user[0]['pw_hash'].encode()) == user[0]['pw_hash'].encode():
            print("It Matches!")
            return(True, user[0]['first_name'], user[0]['id'])
        else:
            print("Password Does not Match")
            errors.append("Login failed")
            return(False, errors)  
        

class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    first_name = models.CharField(max_length=45)
    email = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

python-2/django/integration_project/apps/login_reg_app/views.py
from django.shortcuts import render, redirect
from .models import User

# Create your views here.
def index(request):
  return render(request, "login_reg_app/index.html")

def process(request):
    print"in process method"
    if request.method=='POST':
        print"got method=post"
        print(request.POST)
        response = User.objects.validate_registration(request.POST)
        print("response", response)
        if response[0]:
            print "Register success!!"
            
            context = {
                'first_name': request.POST['ufname'],
                'path': "registered"
            }
            print("context:", context)            
            return render(request, 'login_reg_app/success.html', context)
        else:
            context = {
                'errors': response[1]
            }
            for error in response[1]:
                print"error in response:", error
            return render(request, 'login_reg_app/index.html', context)
    else:
        return render(request, 'login_reg_app/index.html')

def login(request):
    print"in login method"
    if request.method=='POST':
        print"got method=post"
        print(request.POST)
        response = User.objects.validate_login(request.POST)
        print("response", response)
        if response[0]:
            print "Login success!!"
            request.session['id']= response[2]
            print"request.session['id']:", request.session['id'] 
            context = {
                'first_name': response[1],
                'path': "logged in"
            }
            print("context:", context)            
            return render(request, 'login_reg_app/success.html', context)
        else:
            context = {
                'errors': response[1]
            }
            for error in response[1]:
                print"error in response:", error
            return render(request, 'login_reg_app/index.html', context)
    else:
        return render(request, 'login_reg_app/index.html')

def manage_user(request):
    print "Got manage request" 
    users=User.objects.all()
    print ("query:", 50*"*")
    print users.query
    print ("object:",50*"*")
    print users
    print (50*"*")
    for user in users:
        print user.first_name, user.last_name

    context = {
        'users': users
    }

    return render(request, 'login_reg_app/manage.html', context)

def delete_user(request, id):
    print "Got delete request" 
    User.objects.filter(id=id).delete()
    users=User.objects.all()
    print ("query:", 50*"*")
    print users.query
    print ("object:",50*"*")
    print users
    print (50*"*")
    for user in users:
        print user.first_name, user.last_name

    context = {
        'users': users
    }

    return render(request, 'login_reg_app/manage.html', context)

       

python-2/django/integration_project/apps/login_reg_app/templates/login_reg_app/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Log-in / Registration</title>
<meta charset="utf-8">
	<!-- Latest boostrap compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'login_reg_app/css/style.css' %}">
</head>
<body>
	<div id="container">
	<h1>Login Registration</h1>
		<div class= "formbox" id="login_area">				
			<h1>User Login:</h1>
			<form action="/users/login" method="post" id="login_user">
			{% csrf_token %}
				<div class="form-group row">
					<label for="user_email" class="2 col-form-label">User Email:</label><br>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="user_email" name="user_email" placeholder="Enter user's email">
					</div>
				</div>
				
				<div class="form-group row">
					<label for="user_pwd" class="2 col-form-label">Password:</label><br>
					<div class="col-sm-10">
						<input type="password" class="form-control" id="user_pwd" name="password" placeholder="Enter password">
					</div>
				</div>
			   
				<button class="btn btn-primary" type="submit" form="login_user" value="Submit">Submit</button>
			</form>
						
		</div> <!-- end formbox -->

		<div class ="formbox" id="register_area">
			<h1>User Registration Form:</h1>
			<form action="/users/new" id="register_user" method=post>
			{% csrf_token %}
					<div class="form-group row">
						<label for="user_fname" class="2 col-form-label">First Name:</label><br>
						<div class="col-sm-10">
							<input type="text" class="form-control" id="user_fname" name="ufname" placeholder="Enter first name">
						</div>
					</div>
					<div class="form-group row">
						<label for="user_lname" class="2 col-form-label">Last Name:</label><br>
						<div class="col-sm-10">
							<input type="text" class="form-control" id="user_lname" name="ulname" placeholder="Enter last name">
						</div>
					</div>
					<div class="form-group row">
						<label for="user_email" class="2 col-form-label">Email:</label><br>
						<div class="col-sm-10">
							<input type="email" class="form-control" id="user_email" name="uemail" placeholder="Enter email address">
						</div>
					</div>
					<div class="form-group row">
						<label for="user_pwd" class="2 col-form-label">Password:</label><br>
						<div class="col-sm-10">
							<input type="password" class="form-control" id="user_pwd" name="password" placeholder="Enter password">
						</div>
					</div>
					<div class="form-group row">
						<label for="confirm_pwd" class="2 col-form-label">Confirm Password:</label><br>
						<div class="col-sm-10">
							<input type="password" class="form-control" id="confirm_upwd" name="confirm_pwd" placeholder="Confirm password">
						</div>
					</div>
					<button class="btn btn-primary" type="submit" form="register_user" value="Submit">Register as a new user</button>
				</form>				
		</div> <!-- end register box -->
		<div id='errors'> <!-- was div flasharea -->
    	  {% for error in errors %}
    		<p> {{ error }} </p>
    	  {% endfor %}
      </div>

	</div> <!-- end container -->	
</body>
</html>

python-2/django/integration_project/apps/login_reg_app/templates/login_reg_app/manage.html
<!DOCTYPE html>
<html>
<head>
	<title>Manage User Accounts</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'login_reg_app/css/style.css' %}">

</head>
<body>
<div id='container'>
	<div id="navbar">
	      <ul>
	        <li><a href=" {% url 'courses:index' %} ">Manage (add/delete) Courses</a></li>
	        <!-- <li><a href=" {% url 'login:manage_user' %} ">Manage Users</a></li>  -->
	        <li><a href=" {% url 'courses:enroll' %} ">Enroll Users </a></li>  
	        <li><a href=" {% url 'time-display:index' %} ">Time-Display</a></li>
	        <li><a href=" {% url 'ninja-gold:index' %} ">Ninja-Gold</a></li>
	        <li><a href=" {% url 'random-word:index' %} ">Random Word</a></li>
	      </ul>
	 </div> <!-- end navbar -->
	<div id='index_inset'>
	{% for user in users %}
	 <p>{{ user__Course.name }}</p>

	{% endfor %}
	<h1>View/delete registered user accounts</h1>
		
		<div id='summary_display'>
			<h2>Users</h2>
			<table class="table table-bordered">
				<tr>
					<th>First Name</th><th>Last Name</th><th>Date Added</th><th>Actions</th>
				</tr>
				{% for user in users %}
				<tr>
					<td>{{user.first_name}}</td>
					<td>{{user.last_name}}</td>
					<td>{{ user.created_at}}</td>
					<td><a href="{% url 'login:delete_user' id=user.id %}", method='POST'>delete</a></td>
				</tr>					
				{% endfor %}
			</table>
		</div>
	</div>
</div>
</body>
</html>

python-2/django/integration_project/apps/login_reg_app/templates/login_reg_app/success.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  {% load staticfiles %}
	<link rel="stylesheet" href="{% static 'login_reg_app/css/style.css' %}">

  <title>Login Success</title>
</head>
<body>

  <div id='container'>
    <div id="navbar">
      <ul>
        <li><a href=" {% url 'courses:index' %} ">Manage (add/delete) Courses</a></li>
        <li><a href=" {% url 'login:manage_user' %} ">Manage Users</a></li> 
        <li><a href=" {% url 'courses:enroll' %} ">Enroll Users </a></li>  
        <li><a href=" {% url 'time-display:index' %} ">Time-Display</a></li>
        <li><a href=" {% url 'ninja-gold:index' %} ">Ninja-Gold</a></li>
        <li><a href=" {% url 'random-word:index' %} ">Random Word</a></li>
      </ul>
 </div> <!-- end navbar -->
  <h1>Login & Register Success</h1>
    <div id='wrapper'>
	<h2>Success!  Welcome {{ first_name }}!</h2>
    <h2>You've successfully {{ path }}</h2>
    </div> <!-- end wrapper -->
  </div> <!-- end container -->
  
</body>
</html>